// This file is auto-generated by graph.py
const taxDataAustralia = [
  { year: 1945, rate: 75 },  // 1955–1983
  { year: 1951, rate: 75 },  // 1955–1983
  { year: 1955, rate: 67 },  // 1955–1983
  { year: 1955, rate: 67 },  // 1955–1983
  { year: 1983, rate: 60 },  // 1983–1985
  { year: 1985, rate: 49 },  // 1985–1990
  { year: 1990, rate: 47 },  // 1990–2004
  { year: 2004, rate: 47 },  // 2004–2007
  { year: 2025, rate: 45 }   // 2025
];

const taxDataUS = [
  { year: 1913, rate: 7 },
  { year: 1918, rate: 77 },
  { year: 1925, rate: 25 },
  { year: 1932, rate: 63 },
  { year: 1944, rate: 94 },
  { year: 1964, rate: 77 },
  { year: 1965, rate: 70 },
  { year: 1982, rate: 50 },
  { year: 1987, rate: 38.5 },
  { year: 1988, rate: 33 },
  { year: 1991, rate: 31 },
  { year: 1993, rate: 39.6 },
  { year: 2001, rate: 35 },
  { year: 2013, rate: 39.6 },
  { year: 2018, rate: 37 },
  { year: 2025, rate: 37 }
];

const commonLayout = {
  "autosize": true,
  "xaxis": {
    "title": "Year",
    "tickangle": -45,
    "showgrid": true,
    "gridcolor": "#f0f0f0",
    "range": [1910, 2030],
    "dtick": 10
  },
  "yaxis": {
    "title": {
      "text": "Tax Rate (%)",
      "standoff": 20,
      "font": {
        "size": 12
      }
    },
    "range": [0, 100],
    "tickformat": ".0f",
    "showgrid": true,
    "gridcolor": "#f0f0f0"
  },
  "margin": {
    "l": 100,
    "r": 150,
    "t": 60,
    "b": 100,
    "pad": 4
  },
  "showlegend": false
};

const commonConfig = {
  "displayModeBar": false,
  "responsive": true
};

window.graphs = [
  {
    "id": "demoPlot",
    "data": [
      {
        "x": taxDataAustralia.map(point => point.year),
        "y": taxDataAustralia.map(point => point.rate),
        "type": "scatter",
        "mode": "lines+markers",
        "name": "Top Tax Rate",
        "fill": "tozeroy",
        "fillcolor": "rgba(55, 83, 109, 0.1)",
        "line": {
          "shape": "hv",
          "color": "#37536D",
          "width": 2
        },
        "marker": {
          "color": "#37536D"
        },
      }
    ],
    "layout": {
      ...commonLayout,
      "title": "Top Tax Rate in Australia"
    },
    "config": {
      ...commonConfig
    }
  },
  {
    "id": "usTaxPlot",
    "data": [
      {
        "x": taxDataUS.map(point => point.year),
        "y": taxDataUS.map(point => point.rate),
        "type": "scatter",
        "mode": "lines+markers",
        "name": "US Top Tax Rate",
        "fill": "tozeroy",
        "fillcolor": "rgba(220, 53, 69, 0.1)",
        "line": {
          "shape": "hv",
          "color": "#DC3545",
          "width": 2
        },
        "marker": {
          "color": "#DC3545"
        },
      }
    ],
    "layout": {
      ...commonLayout,
      "title": "Top Tax Rate in the United States"
    },
    "config": {
      ...commonConfig
    }
  }
];